### PR TITLE
feat: Add tvOS support

### PR DESCRIPTION
**Pull request by alexzchut**
## Description
Adding tvOS support to allow using AEP with tvOS

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexzchut** [comment]
@cdhoffmann Can you please add these changes too to be included in the next release along with the https://github.com/adobe/aepsdk-core-ios/pull/798

**Review by cdhoffmann — APPROVED** [review]

**Comment by cdhoffmann** [comment]
@alexzchut Thank you. These changes will be included in the next release.

**Comment by alexzchut** [comment]
@cdhoffmann Can you please also look at these 2, it is just podspec update there and very important to have them in too:
https://github.com/adobe/aepsdk-media-ios/pull/53
https://github.com/adobe/aepsdk-analytics-ios/pull/69

**Comment by cdhoffmann** [comment]
@alexzchut Those two repositories belong to another team. They are aware and will get to tvOS support at their earliest convenience. Thank you for your patience.

**Pull request merged**
